### PR TITLE
Enhancement/teststructure

### PR DESCRIPTION
**Pull request by MrHug**
I have restructured the tests to have a clear distinction between unit tests and integration tests (only to conclude that there are very few of the first :wink:)

Notes:
- Tests are now split over `/src/tests/unit/java` and `/src/tests/integration/java`.
- TestSuites can be found in `/src/tests/integration/java`
- Packages in `integration` are now called `xxx.tests.integration.yyy` so that unit tests and integration tests for the same class can share a name.
- A new gradle command `intTest` has been created that runs only the integration tests. All other commands should remain operational.

This is a start for issue #384.

### CODE REVIEW

**Comment by MrHug** [comment]
Hmm apparently the travis build failed due to some dependency failing to download?

>Execution failed for task ':syncany-cli:instrument'.
> Could not resolve all dependencies for configuration ':syncany-cli:cobertura'.
   > Could not determine artifacts for component 'xml-apis:xml-apis:2.0.2'
       Could not HEAD 'https://repo1.maven.org/maven2/xml-apis/xml-apis/2.0.2/xml-apis-2.0.2.jar'. ?Received status code 503 from server: Connection timed out

**Comment by cr0** [comment]
In that case Philipp has to restart the build process.

**Comment by pimotte** [comment]
@cr0, I can do that too (and I just did), so I assume you can too.

**Comment by MrHug** [comment]
Hmm ok, because I have been changing `gradle` settings, so if this fails properly I might have made an error somewhere ;) Locally running tests etc through gradle went fine, but I'm still curious to see how it will do here.

**Comment by pimotte** [comment]
Unfortunately, something is wrong. Did you use ./gradlew testGlobal when testing locally? It seems travis only ran the ones for which the package name did not change. Which, as I recall, should be none of them (I think the ones that were ran should have "unit" somewhere in the package name)

**Comment by MrHug** [comment]
Currently only the integration tests have `integration` added as an extra package, the others have no extra package name, but are in the `unit` folder (integration are in the `integration` folder too ofc :wink:)

If preferred I can also add the `.unit.` package to the unit tests?

As discussed in IRC, locally this gives me the correct result.

**Comment by MrHug** [comment]
Alright, so this becomes a bit more mysterious... A clean clone also fails to run the `integration` tests, yet a recursive diff only gives differences in the build/git folders and not in anything gradle related..

**Comment by pimotte** [comment]
The folderpath for the ScenarioTests is the wrong way around (integration/tests instead of tests/integration). The rest looks good to me.

**Comment by MrHug** [comment]
Fixed :)

**Comment by pimotte** [comment]
Great start! :+1:

**Comment by binwiederhier** [comment]
:+1:

**Pull request merged**
