### PR TITLE
Feature/issue364 (follow-up)

### PR DESCRIPTION
**Pull request by pimotte**
Building on the work of @jdonkervliet and @thegeman.

Things that still need to be done:

- [x] Fixing the handling of events emitted by UpOperation.
- [ ] Perhaps an extra test here and there.

@binwiederhier, I think all the comments in the original PR have been handled. Could you take another look at this?

### CODE REVIEW

**Comment by binwiederhier** [comment]
Cool. I'll look at this tomorrow.

**Comment by binwiederhier** [comment]
This is a dry review. 

(1) I remember saying this before, but why do we have to pass the `firstFile` index into the `deduplicate()` function? Can't we just adjust the file list and only pass it in instead?

(2) Minor: Instead of signalling with an empty dbv, I'd check by reference. So basically just use `final DatabaseVersion EMPTY_DATABASE_VERSION = new DatabaseVersion()` instead. And the while loop would be `while (databaseVersion != EMPTY_...)`.

(3) Shockingly. This is it for now. It looks very sound and besides the classic indention and style issues, I don't see a problem with that. Good work and re-work. I will have to actually test this myself before we merge it. 

(4) How far along is this? When do you think it's merge-ready? I suggest that we merge this right after the next release (separate from everything else), just like with #366, so that we can test it for a while in a live environment.

**Comment by thegeman** [comment]
@binwiederhier, quick update from me and @jdonkervliet. We have been quite busy doing all sorts of writing and studying, so we lost track of this a bit. We discussed with Pim to do some more contributions in a week or two when exams are over. Thank you, Pim, for picking up where we left.

(1) The only reason for including the `firstFile` parameter is that `DeduperListener.onFileStart` method requires a file index. Without `firstFile` we would not be able to determine the index across multiple invocations of `Deduper.deduplicate`. If you deem the file index no longer relevant to the `onFileStart` method, we can replace the list and index with a queue.

Remaining points are probably best answered by Pim.

**Comment by binwiederhier** [comment]
@thegeman Thanks for the update. Your studies are always more important than some open-source project so don't feel bad! 

ad (1): Apparently we don't even use the index in `DeduperListener.onFileStart`. So we can definitely get rid of it :+1:

**Comment by pimotte** [comment]
I'll pick up (1) and (2). I agree on 4. I've done some testing myself and it seems to work.

The merging of this will actually be the point where I move all the things I currently have in Owncloud to Syncany.

**Comment by pimotte** [comment]
I just fixed some tests. @binwiederhier you'll probably want to look at 2c35f7c.

The only test that is still failing is the one that calls up while writing is still in progress (testUpWhileWritingFile). The reason it fails is because there is a databaseversion. However, this databaseversion only contains chunks/multichunks and no file history. On the one hand, I don't really see this as a problem. On the other hand, it seems kind of awkward behaviour. Opinions?

**Comment by celogeek** [comment]
Hi,

I'm testing this branch. I have a very large amount of files in a directory (+250k) for 4 GB.

I can tell that up is smoother and faster.

Also, it seems to only improve the "up" command. When I have finish to upload, and I start to sync the freshly uploader backup, into a brand new directory, I have exactly the same issue as with up.

It is very long, and use a very high amount of memory and cpu.

also got this with 2GB setup for memory limit:

```
Downloading multichunk 355/355 ...Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at java.util.Formatter.parse(Formatter.java:2547)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2927)
	at org.syncany.database.DatabaseConnectionFactory.getStatement(DatabaseConnectionFactory.java:98)
	at org.syncany.database.dao.AbstractSqlDao.getStatement(AbstractSqlDao.java:50)
	at org.syncany.database.dao.FileVersionSqlDao.writeFileVersions(FileVersionSqlDao.java:84)
	at org.syncany.database.dao.FileHistorySqlDao.writeFileHistories(FileHistorySqlDao.java:81)
	at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:149)
	at org.syncany.database.dao.DatabaseVersionSqlDao.writeDatabaseVersion(DatabaseVersionSqlDao.java:108)
	at org.syncany.database.SqlDatabase.writeDatabaseVersion(SqlDatabase.java:182)
	at org.syncany.operations.down.DownOperation.persistDatabaseVersion(DownOperation.java:603)
	at org.syncany.operations.down.DownOperation.persistDatabaseVersions(DownOperation.java:590)
	at org.syncany.operations.down.DownOperation.applyWinnersBranch(DownOperation.java:470)
	at org.syncany.operations.down.DownOperation.execute(DownOperation.java:190)
	at org.syncany.cli.DownCommand.execute(DownCommand.java:56)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
	at org.syncany.Syncany.main(Syncany.java:52)
```

Do you thing it is possible to also download by smaller chunk ?

Cheers

**Comment by pimotte** [comment]
@celogeek great to hear that you've noticed improvement. That it only improves for Up is more or less to be expected, since this branch concerns itself only with Up. I had hoped the smaller transactions would automatically fix Down as well, but now I know for sure this is not the case. 

Fixing the memory issues is next on my list after bringing this to the finish line.

**Comment by celogeek** [comment]
@pimotte ok nice. I will be glade to test again. For now down is not usable anymore on large amount of files.
Great work, seems promising.

**Pull request merged**
