### PR TITLE
Change 'sy init -t' to 'sy init -T'

### PR DESCRIPTION
**Pull request by binwiederhier**
This has annoyed me for a while. This changes the default behavior of `sy init` to create the target folder/bucket/whatever instead of failing.

### CODE REVIEW

**Comment by cr0** [comment]
Only a suggestion: Perhaps it might be better to ask if the folder should be created after init failed because of that error instead of creating it in the first place?

**Comment by binwiederhier** [comment]
That would be the ultimate solution, but as you as aware, the AbstractInitCommand is not the easiest class to tackle. And it would also mean having to provide another callback/hook for the GUI...

**Comment by cr0** [comment]
Well, then open an issue for that and we'll add that feature later ;) But creating the target is definitely better than the current solution, so go ahead.

**Comment by binwiederhier** [comment]
So I will.

**Pull request merged**
