### PR TITLE
Feature/issue289 sonarqube

### LINKED ISSUE #289: Static code analysis: Provide SonarQube Gradle task
[SonarQube](http://www.sonarqube.org/) is a pretty awesome static code analysis tool. I'd like to provide our developers with always up-to-date code analysis results (such as [in the example](http://nemo.sonarqube.org/)). 

If someone would like to create a [Gradle task](http://www.gradle.org/docs/current/userguide/sonar_runner_plugin.html) that can be run by Travis with every commit, I'll provide a SonarQube server to report the results to. The JDBC credentials must be read from an environment variable (which can be encrypted with Travis).

Any voluntees? @MrHug?

### PR DESCRIPTION
**Pull request by MrHug**
I set up the sonar profiles, but will make a wiki page about how I've set it up. In addition I've tried to create a script that will only execute the sonar task if it is not a PR, obviously this will require some testing on travis :wink:

Closes #289.

### CODE REVIEW

**Comment by MrHug** [comment]
I've written something on the wiki about it [here](https://github.com/syncany/syncany/wiki/Static-code-analysis:-SonarQube)

**Comment by binwiederhier** [comment]
Good stuff!

(a) The Wiki article is very nice. Can we add the ruleset to the repo in `gradle/sonarqube/something.xml`?  Does sonarqube complain if we pretty print it?

(b) I remember sonarqube takes ages for its analysis. I can't really tell from the Travis time how much that adds to our build time, because apparently it hasn't run since 30 Dec 2014?! Do you think we should only run this every other day? Like: Only on `master`, or only every second day?

(c) Do you know if sonarqube updates itself? If not, do you know if there are plugins/mechanisms to ensure that we're not vulnerable to any security-relevant bugs?

(d) Right now I have to open the MySQL port to the outside world to publish the sonar results. Do you know if we can somehow get around that?

**Comment by MrHug** [comment]
> Can we add the ruleset to the repo in `gradle/sonarqube/something.xml`? 

Yes

>  Does sonarqube complain if we pretty print it?

No clue, but I'll find out :wink:

> Do you think we should only run this every other day?

Currently it only runs for new pushes to develop that are not pull requests, similar to your upload script and at the very end of the script (i.e. after all actions, including uploading) have been completed. As a result I think it should be fine to run it for every push to `develop`/`master`

> Do you know if sonarqube updates itself?

It does not and I do not know how to do this other than through the visual "update center" in the SonarQube interface...

> Right now I have to open the MySQL port to the outside world to publish the sonar results. 

Are you sure? Is opening port 9000 and enabling guest access somehow not enough? 

I don't have time to look into this now, but will take a look tomorrow :)

**Comment by binwiederhier** [comment]
ad (b): How long does a single run take? If it's more than 2min I think we should reconsider running it with every commit. It already takes 10minutes or so to build the whole thing. 

ad (c): This is really important to me. If we do not find a way to auto-update and/or alert on updates, I will not keep letting this complex piece of software run on the Syncany server.

ad (d): Afaik we need to open the MySQL port to upload the analysis results, at least that's what I did last time: https://github.com/syncany/syncany/pull/395/files#diff-3e9dd02f6a884dc3f5d3f652ff7cd4ebR3

**Comment by MrHug** [comment]
a): Prettyprinting seems fine, have added the xml file.

b): Ideally it would incur only 1 minute or so extra time cost, because SonarQube shouldn't have to rerun the tests, yet in order to accomplish that I think we require the change made in commit 876ddc06b98d15b03181d543cc1e5515c823f4d0... It's not very neat, and perhaps a separate script for the gradle command as a whole would be preferred but I think it does the job.

c) I really can't find anything for this... I suppose there is no way to run it somewhere else? Otherwise the best option would be to follow their CSS feed or something?

d) They seem to recommend running the analyzer on the same network as the MySQL server to resolve this, so we can either try to set something up that triggers a build of this on the Syncany servers (though I would argue that opening up a port for that might be even worse) or keeping the MySQL server open. 

The way I see it though is that running sonarqube + MySQL somewhere else entirely would be the preferred way of doing things. After all Sonar + this MySQL db will not hold any information that can not be obtained by anyone else with a clone of this repository. Obviously the Syncany server should remain secure, but the system for Sonar + SQL would not have to be as secure I'd say :wink:

**Comment by binwiederhier** [comment]
(a) Cool.

(b) Okay. The build has been running [for >25 minutes now](https://travis-ci.org/syncany/syncany/builds/52798543). I think it's safe to say that we should NOT do this for every commit. IMHO not even for any commit on `develop`. Every commit on `master` should be good.

(c)+(d) This is really important. We need to know about updates. Can you try to research this a bit more? I've opened the MySQL port again. I might try to limit it to the Travis port range.

**Comment by binwiederhier** [comment]
Travis killed the build after 43 minutes...

**Comment by MrHug** [comment]
Wow... Just wow...

Inspecting the log has told me that the analysis actually finished though (in 20 minutes, but still it finished). It just seemed unable to upload the results... I'll take a look at c + d tomorrow, but perhaps this uploading requires some other fix? Are you sure the proper ports are open?

**Comment by binwiederhier** [comment]
Ports are definitely open. But the database doesn't seem to indicate activity. I'm not sure if the credentials in the env variables still work. Maybe I should double check them.

`sonar.log` doesn't show any activity. The only activity in `access.log` is this:

```
199.91.171.26 - - [02/03/2015:21:52:11 +0100] "GET /sonarqube/api/server/version HTTP/1.1" 200 5 "-" "SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:11 +0100] "GET /sonarqube/batch_bootstrap/index HTTP/1.1" 200 68 "-" "SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:16 +0100] "GET /sonarqube/batch/sonar-batch-maven-compat-4.5.1.jar HTTP/1.1" 200 18461364 "-" "SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:20 +0100] "GET /sonarqube/batch/global HTTP/1.1" 200 - "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:21 +0100] "GET /sonarqube/deploy/plugins/index.txt HTTP/1.1" 200 704 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:22 +0100] "GET /sonarqube/deploy/plugins/findbugs/sonar-findbugs-plugin-3.1.jar HTTP/1.1" 200 6228395 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:22 +0100] "GET /sonarqube/deploy/plugins/cpd/sonar-cpd-plugin-4.5.1.jar HTTP/1.1" 200 28364 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:23 +0100] "GET /sonarqube/deploy/plugins/core/sonar-core-plugin-4.5.1.jar HTTP/1.1" 200 198033 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:23 +0100] "GET /sonarqube/deploy/plugins/java/sonar-java-plugin-2.9.1.jar HTTP/1.1" 200 2348992 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:23 +0100] "GET /sonarqube/deploy/plugins/dbcleaner/sonar-dbcleaner-plugin-4.5.1.jar HTTP/1.1" 200 17305 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:23 +0100] "GET /sonarqube/deploy/plugins/l10nen/sonar-l10n-en-plugin-4.5.1.jar HTTP/1.1" 200 3799 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:23 +0100] "GET /sonarqube/deploy/plugins/cobertura/sonar-cobertura-plugin-1.6.3.jar HTTP/1.1" 200 10325 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:24 +0100] "GET /sonarqube/deploy/plugins/emailnotifications/sonar-email-notifications-plugin-4.5.1.jar HTTP/1.1" 200 599774 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:24 +0100] "GET /sonarqube/deploy/plugins/design/sonar-design-plugin-4.5.1.jar HTTP/1.1" 200 16106 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:24 +0100] "GET /sonarqube/deploy/jdbc-driver.txt HTTP/1.1" 200 64 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:24 +0100] "GET /sonarqube/deploy/mysql-connector-java-5.1.27.jar HTTP/1.1" 200 872300 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:32 +0100] "GET /sonarqube/api/server HTTP/1.1" 200 55 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:52:39 +0100] "GET /sonarqube/batch/project?key=syncany&amp;preview=false HTTP/1.1" 200 - "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:36 +0100] "GET /sonarqube/api/server/version HTTP/1.1" 200 5 "-" "SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:36 +0100] "GET /sonarqube/batch_bootstrap/index HTTP/1.1" 200 68 "-" "SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:40 +0100] "GET /sonarqube/batch/sonar-batch-maven-compat-4.5.1.jar HTTP/1.1" 200 18461364 "-" "SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:41 +0100] "GET /sonarqube/batch/global HTTP/1.1" 200 - "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:41 +0100] "GET /sonarqube/deploy/plugins/index.txt HTTP/1.1" 200 704 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:43 +0100] "GET /sonarqube/deploy/plugins/findbugs/sonar-findbugs-plugin-3.1.jar HTTP/1.1" 200 6228395 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:43 +0100] "GET /sonarqube/deploy/plugins/cpd/sonar-cpd-plugin-4.5.1.jar HTTP/1.1" 200 28364 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:43 +0100] "GET /sonarqube/deploy/plugins/core/sonar-core-plugin-4.5.1.jar HTTP/1.1" 200 198033 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:44 +0100] "GET /sonarqube/deploy/plugins/java/sonar-java-plugin-2.9.1.jar HTTP/1.1" 200 2348992 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:44 +0100] "GET /sonarqube/deploy/plugins/dbcleaner/sonar-dbcleaner-plugin-4.5.1.jar HTTP/1.1" 200 17305 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:44 +0100] "GET /sonarqube/deploy/plugins/l10nen/sonar-l10n-en-plugin-4.5.1.jar HTTP/1.1" 200 3799 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:44 +0100] "GET /sonarqube/deploy/plugins/cobertura/sonar-cobertura-plugin-1.6.3.jar HTTP/1.1" 200 10325 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:44 +0100] "GET /sonarqube/deploy/plugins/emailnotifications/sonar-email-notifications-plugin-4.5.1.jar HTTP/1.1" 200 599774 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:44 +0100] "GET /sonarqube/deploy/plugins/design/sonar-design-plugin-4.5.1.jar HTTP/1.1" 200 16106 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:44 +0100] "GET /sonarqube/deploy/jdbc-driver.txt HTTP/1.1" 200 64 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:45 +0100] "GET /sonarqube/deploy/mysql-connector-java-5.1.27.jar HTTP/1.1" 200 872300 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:52 +0100] "GET /sonarqube/api/server HTTP/1.1" 200 55 "-" "Sonar SonarQubeRunner/2.4"
199.91.171.26 - - [02/03/2015:21:57:57 +0100] "GET /sonarqube/batch/project?key=syncany&amp;preview=false HTTP/1.1" 200 - "-" "Sonar SonarQubeRunner/2.4"
```

**Comment by MrHug** [comment]
As Travis indicates that it only started uploading results at `21:14:57.078 INFO  - Store results in database`, I'm a bit puzzled about times... Is it possible there is an hour of time difference between Travis & the Syncany server? If so  that would have the original connection:
`20:52:24.825 INFO  - Create JDBC datasource for jdbc:mysql://syncany.org:3306/syncanysonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance`
match up roughly with the main activity in the syncany log... Yet it still is not a perfect match... Strange things all around, let me know once you've checked the credentials (this analysis should never take this long, I mean Travis can't be all that much slower than my laptop now can it? :wink:)

**Comment by MrHug** [comment]
@binwiederhier Can you restart it once maybe? I'm going to get some sleep now, but will check up on this tomorrow.

**Comment by binwiederhier** [comment]
Date on the Syncany server is now Mon Mar  2 23:06:41 CET 2015. As I recall, there were multiple 10-minute breaks (in a blocked state). I have not checked the credentials yet. Hit me up tomorrow and I will restart it then. I don't want to leave it in a broken state.

**Comment by MrHug** [comment]
Well it's a little over a day, but can you give this another go? Like I said earlier, I suspect some port/credentials issue was disallowing Travis to actually upload the results to the database, as the analysis was fully done and the Sonar logs showed no record of an upload attempt at that time.

**Comment by binwiederhier** [comment]
Seeing as there are multiple large time gaps, I honestly don't know if I want this to run with every commit or even on master. Running it occasionally (e.g. via a trigger in the commit message) would be nice (like `git commit -m"Do X, Y and Z #sonar"`). Can you see if you can find out anything about these gaps? Because I remember having them even on the local machine. I'll do another test run later.

Gaps:
```
20:52:20.300 INFO - Load global referentials...

...

20:52:48.302 INFO - Load module settings  
       // 1:30 minute gap
20:54:18.868 INFO - Loading rules...

...
20:54:23.624 INFO - 41 files indexed
      // 1 minute gap
20:55:12.509 INFO - Quality profile for java: Syncany

...

20:55:57.941 INFO - Execute decorators...
     // 30 second gap
20:56:31.279 INFO - ------------- Scan syncany-lib
...
20:56:32.606 INFO - 475 files indexed
        // 10 minute gap. This has nothing to do with the database. I've seen this locally before.
21:05:01.906 INFO - Quality profile for java: Syncany  

...

21:05:25.854 INFO - Package design analysis...
       // 2:30 minute gap
21:07:58.360 INFO - Package design analysis done: 152506 ms
...
21:08:38.194 INFO - Execute decorators...
      // 6 minute gap
21:14:00.677 INFO - ------------- Scan syncany-util

...

21:14:57.078 INFO - Store results in database

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by MrHug** [comment]
These times are the times it's actually doing analysis (at least the execute and indexing gaps). 
I can try to see what happens if I reduce the quality profile in size in bit, it currently has quite a lot of rules...

As for the commit message, this sounds like a good idea, only question I would have if is Travis can access the message?

**Comment by binwiederhier** [comment]
Hehe; last commit in GUI:

```
$ git log -1 --pretty=%B
Duh.
```

@MrHug As a Sonar expert, would you mind also checking on https://github.com/syncany/syncany-plugin-dropbox/pull/3#issuecomment-77331666? Thanks!

**Comment by binwiederhier** [comment]
ad "last commit message": see https://github.com/syncany/syncany/blob/ade3f38abae0d1556a2a679eeb7637d61cd01f68/gradle/gradle/helpers.gradle#L37

**Pull request merged**
