### PR TITLE
Do not add enums to option description

### PR DESCRIPTION
**Pull request by cr0**
because it interferes with the GUI (see syncany/syncany-plugin-s3#5)

Output:
```
$ sydev init s3
Choose a storage plugin. Available plugins are: dropbox, local, s3, sftp, webdav
Plugin: s3

Connection details for s3 connection:
- Access Key: ads
- Secret Key (not displayed): 
- Bucket: asd
- Choose 'Location' from ASIA_PACIFIC, ASIA_PACIFIC_NORTHEAST, ASIA_PACIFIC_SINGAPORE, ASIA_PACIFIC_SOUTHEAST, ASIA_PACIFIC_SYDNEY, ASIA_PACIFIC_TOKYO, EU_FRANKFURT, EU_IRELAND, EUROPE, GOVCLOUD_FIPS_US_WEST, GOVCLOUD_US_WEST, SOUTH_AMERICA_EAST, SOUTH_AMERICA_SAO_PAULO, US_WEST, US_WEST_NORTHERN_CALIFORNIA, US_WEST_OREGON, GOOGLE_US, GOOGLE_ASIA, GOOGLE_EU: 
```

### CODE REVIEW

**Comment by binwiederhier** [comment]
Lgtm

**Comment by binwiederhier** [comment]
Maybe `Location, choose from X, Y, Z` instead of the quotes thing.

**Comment by cr0** [comment]
Yep that's better

**Comment by binwiederhier** [comment]
merge at will :)

**Pull request merged**
