### PR TITLE
Coveralls integration

### PR DESCRIPTION
**Pull request by cr0**
Pull request to see if coveralls is submitting coverage changes via github status api

https://coveralls.io/r/syncany/syncany

*ignore for now*

### CODE REVIEW

**Comment by binwiederhier** [comment]
We used to have coveralls integration, but it was buggy as hell. Coveralls missed covered lines, simply didn't display results or take >1hr to run. But we do have coverage results on our own. Why would we need coveralls?

**Comment by cr0** [comment]
I thought it would be nice to see how pull requests affect the coverage status. And since coveralls uses the github API to submit those stats...



(of course with the commenting feature switched off)

**Comment by binwiederhier** [comment]
I guess as long as it doesn't hurt :)

**Comment by cr0** [comment]
Since coverage is also done by cobertura it's identical to the one from your Syncany's API badge. Also, the check is submitted via API. I like it ;)

Do we want to set limits for *COVERAGE THRESHOLD FOR FAILURE* or *COVERAGE DECREASE THRESHOLD FOR FAILURE*

**Comment by binwiederhier** [comment]
Whut? 70% -> red in the badge. I think that's a good failure threshold

**Pull request merged**
