### PR TITLE
Support gradle 6+

### LINKED ISSUE #632: Deprecated Gradle features were used in this build, making it incompatible with Gradle
Hi,

When I try to compiling from source I get this:

`Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.`

### PR DESCRIPTION
**Pull request by cr0**
Hey guys,

long time no see. I hope you are all doing well in these special times!

I felt somehow nostalgic and wanted to try out syncany again, however, the very outdated gradle and dozens of deprecated warnings were a showstopper. So I quickly upgraded gradle to 6.8 and made everything ready for gradle 7.x. This closes #632 

As far as I can see, all tasks are still working as expected. The result is a runnable version of syncany.
@pimotte I saw that you are still actively merging pull requests - would you mind doing it or should I do it myself?

```
.\gradlew installDist

> Task :syncany-lib:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :syncany-cli:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

BUILD SUCCESSFUL in 5s
11 actionable tasks: 11 executed

.\gradlew -version

------------------------------------------------------------
Gradle 6.8
------------------------------------------------------------

Build time:   2021-01-08 16:38:46 UTC
Revision:     b7e82460c5373e194fb478a998c4fcfe7da53a7e

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15.0.1 (Oracle Corporation 15.0.1+9-18)
OS:           Windows 10 10.0 amd64
```

### CODE REVIEW

**Comment by binwiederhier** [comment]
That's awesome. I often think about how great this time was with syncany. It was a wild ride. We likely did too much, we should have concentrates on some basics first. 

Let me know if there is anything I can do to help. I think I can get my irc bridge back up and running too if need be. Or we can make a slack channel somewhere.

**Comment by cr0** [comment]
Hey Philipp! 
Yes, we got lost in features because everything sounded so cool, no matter what.
But hey, I considered syncany a project to push my Java skills and it was a playground at some point for all of us. However, still nice to see that syncany is still considered a valid solution for syncing stuff -- I am still sad that I've never managed to get us a Dropbox production key (see #480). 

I was happy to see that the website and api are still working. But maybe you noticed that travis.org will merge with travis.com so maybe we should keep at least an eye on this. 
We can use discord but I am afraid there is no much of a community anymore :(

**Comment by pimotte** [comment]
Hey guys,

@cr0 feel free to merge yourself, whatever you're working on:)

The travis issue is a real problem and it has been unstable for me in other projects too. They have stopped the process for giving out credits. I see migration to github actions as one of the primary options.

Best regards:)

**Comment by binwiederhier** [comment]
I have recently ventured into the world of GitHub actions and it looks to be able to do exactly what travis did for us. I don't think it'll be hard to port. 

I have never used discord, only slack and irc. But I'll join whatever channel you set up if you want ;-)

**Comment by binwiederhier** [comment]
@pimotte I still work in th same Norwalk office, although I've been working from home for almost a year as you can imagine. Datto has changed a lot but many things are still the same. I hope you landed alright. ;-)

**Pull request merged**
