### PR TITLE
Automatic OAuth token handling

### PR DESCRIPTION
**Pull request by cr0**
This PR makes the OAuth process much more user friendly by automatically receiving tokens from a provider. This is much more common than copy-pasting a token from website (c.f. several email clients which use google's mail API).

*Some OAuth background*
There are several possibilities how OAuth can work. One is that a provider forwards an access token through a callback URL. Sometimes, a provider uses the query parameters (the part behind the `?`) but in order to prevent token stealing (or suppress the logging of a token) by a server provider it is also possible to use the hash or fragment path of an URL (the part behind a `#`). The fragment path is only delivered to a client (=browser), not a web server. It could be possible that some providers only support OAuth using callback URLs, hence we need to handle such cases. 

*How does it work?*
If Syncany detects an OAuth enabled `TransferSetting` plugin, it starts up a web server on a random (or fixed) port and generates a callback URL which should be used during the OAuth process. In order to be flexible for different OAuth processes, the token server uses so-called `Interceptors` and `Extractors`. `Interceptors` handle different HTTP requests and react upon them. `Extractors` are used to actually extract the token from the callback URL. Of course, the process supports protection measures against CSRF attacks, namely the `state` parameter from the OAuth RFC.

I created [a gist](https://gist.github.com/cr0/2ee0328d54b016d259a3) with an OAuthWebListener enabled DropboxTransferSettings class.

The process flow is as follows. First, a `OAuthTokenWebListener` is build on the basis of an already existing `OAuthGenerator`. It is possible to use a different first interceptor and an token extractor. I commented the sample code below because I think it's easy to get the idea on the basis of working code.
```java
OAuthTokenWebListener twl = OAuthTokenWebListener
	.forId("testSite") // each token listener needs an individual id
	.setTokenInterceptor(new OAuthTokenInterceptors.RedirectTokenInterceptor())
	.setTokenExtractor(new OAuthTokenExtractors.NamedQueryTokenExtractor("access_token", "state"))
	.build();

URI baseUri = twl.start(); // start the token listener server
Future<OAuthTokenFinish> submittedFutureToken = twl.getToken(); // wait for a token and return a future reference
OAuthTokenFinish submittedToken = submittedFutureToken.get(); // get the actual token. waits if the token hasn't already been transmitted. 
```
Since Dropbox does not use the fragment path of the url to transmit the token, it is sufficient to simply redirect the response to the extractor (thus the `RedirectTokenInterceptor`). The token is embedded in the query parameters named as `access_token`, hence we use a `NamedQueryTokenExtractor("access_token", "state")`. To protect the OAuth process, Dropbox supports a `state` parameter.

As you can see from the gist, there is very little to do in order to enable the listener service. However, the benefit for an enduser is huge!

*And because screenshots are always better than text*

Process start:
screen shot 2015-03-31 at 13 45 36

User accepts the authorization request:
screen shot 2015-03-31 at 13 46 16

User disallow the authorization request:
screen shot 2015-03-31 at 13 49 32

This PR does not add additional runtime dependencies, although, `htmlunit` is required to run the tests.

### CODE REVIEW

**Comment by cr0** [comment]
Well now we've duplicates in this branch. How could I fix this on a filesystem which is case-insensitive? help pls :(

**Comment by pimotte** [comment]
I dry-reviewed this and it looks good to me. For some reason the build is stalling, so we'll need to look at that before merging.

**Comment by binwiederhier** [comment]
Wow. How awesome is this?! Great job Christian. 
I can honestly say that this is beautiful code and we can merge this as is (provided that the Travis issue is solved)! 

I haven't tested this yet, but I'm sure it works just fine. 

Does it still support the old token way? I was wondering because what if browser and Syncany CLI are not on the same machine, e.g. if I connect to Dropbox, but I'm connected to a remote machine via SSH. Does that also work?

**Comment by dmexs** [comment]
Well done. Does this support UPnP for auto-poking holes through consumer routers and other NAT setups?

**Comment by cr0** [comment]
Why is this test stalling? Those two last commits should not cause any tests to fail....

@binwiederhier: Unfortunately, I did not see that use case. So the answer is no, the old token based process is gone. We would need a new flag for init which tells Syncany that we're on a headless device so it's changing its behaviour.

@dmexs: Why should we need this? We cannot use a different redirect URL than `http://localhost:6462/dropbox/` because the OAuth RFC requires the provider to check a redirect against a whitelist (to prevent some attacks). At the moment, that given URL is the only one whitelisted. Whitelisting can only be done be the client id holder which is I for the Dropbox plugin.

**Comment by cr0** [comment]
The old copy-token based mode was readded, although, the new redirect mode is the default. Hence a plugin has to support that mode explicitly and its only activated if the headless flag (--headless) is used.

I updated the Dropbox plugin gist: https://gist.github.com/cr0/2ee0328d54b016d259a3

**Comment by dmexs** [comment]
@cr0 maybe I'm misunderstanding the Amazon Cloud Drive API documentation (https://developer.amazon.com/public/apis/experience/cloud-drive/content/getting-started). To use the "Authorization Code Grant" mode, does that redirect_uri not need to be publically accessible to Amazon?

**Comment by binwiederhier** [comment]
@cr0 Looks good to me. I like the `--headless` option. Good idea! 

(a) I'd love a bit more JavaDoc-ing on the new classes if it's not too much to ask
(b) Can you add the `--headless` option to the bash completion script and the help/man page?
(c) This does not break any of the existing plugins, right? It shouldn't if I understand the code correctly.
(d) Merge if you want to. 

@dmexs I think Amazon will just redirect to that URL via HTTP "Location:". I don't think it has to be publicly accessible. Of course I haven't checked ...

**Comment by cr0** [comment]
a) Do you have any specific things in mind?
b) Yep, can do
c) It *does* break old plugins because [`OAuthGenerator#generateAuthUrl`](https://github.com/syncany/syncany/blob/feature/oauth-callback/syncany-lib/src/main/java/org/syncany/plugins/transfer/oauth/OAuthGenerator.java#L44) gets a redirect uri now. This has to be the default behaviour since the mode with the redirect uri is part of the RFC and is supported by every provider. Showing a token on website however is not supported by all providers, e.g. Amazon does not support it. Afaik, Dropbox is the only oauth enabled plugin at this moment, so no big deal
d) As soon as all open tasks are finished

**Comment by binwiederhier** [comment]
(a) Well, *coughs*, all new classes?! I know I don't always document all the classes, but I try to for the new stuff. Unless of course it's very obvious, like the messages.* classes, for instance. I don't think any of the OAuth stuff is obvious though.
(c) Well, if it only breaks old OAuth plugins, that's fine :)
(d) Cool

**Comment by cr0** [comment]
If no one has any objections, I'll merge this today.

**Comment by binwiederhier** [comment]
No objections, nicely done :+1:

**Pull request merged**
